services:
  metric-server:
    container_name: stori-challenge
    image: stori-challenge:latest
    env_file: "stori.env"
    networks:
      - testing_net

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24